# Generated by Django 4.2.27 on 2026-01-02 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.servicetype', verbose_name='Вид ТО'),
        ),
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.driveaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines_service', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='technique_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.techniquemodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='service.machine', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
