# Generated by Django 4.2.27 on 2026-01-03 17:24

from django.db import migrations


def add_failure_nodes(apps, schema_editor):
    """Добавление узлов отказа"""
    FailureNode = apps.get_model('service', 'FailureNode')
    nodes = [
        'Двигатель',
        'Трансмиссия',
        'Ведущий мост',
        'Управляемый мост',
        'Гидросистема',
        'Подъемное устройство',
    ]
    for node_name in nodes:
        FailureNode.objects.get_or_create(name=node_name)


def add_recovery_methods(apps, schema_editor):
    """Добавление способов восстановления"""
    RecoveryMethod = apps.get_model('service', 'RecoveryMethod')
    methods = [
        'Ремонт узла',
        'Замена узла',
    ]
    for method_name in methods:
        RecoveryMethod.objects.get_or_create(name=method_name)


def remove_failure_nodes(apps, schema_editor):
    """Откат: удаление узлов отказа"""
    FailureNode = apps.get_model('service', 'FailureNode')
    nodes = [
        'Двигатель',
        'Трансмиссия',
        'Ведущий мост',
        'Управляемый мост',
        'Гидросистема',
        'Подъемное устройство',
    ]
    FailureNode.objects.filter(name__in=nodes).delete()


def remove_recovery_methods(apps, schema_editor):
    """Откат: удаление способов восстановления"""
    RecoveryMethod = apps.get_model('service', 'RecoveryMethod')
    methods = [
        'Ремонт узла',
        'Замена узла',
    ]
    RecoveryMethod.objects.filter(name__in=methods).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_failure_nodes, remove_failure_nodes),
        migrations.RunPython(add_recovery_methods, remove_recovery_methods),
    ]
